#!/usr/bin/env bash
# parachuter live demo: the real daemons, side by side, on one laptop.
#
#   ┌──────────────┬──────────────┬──────────────┐
#   │ SENDER       │ LOSSY LINK   │ RECEIVER     │
#   │ (flight)     │ (the radio)  │ (ground)     │
#   ├──────────────┼──────────────┼──────────────┤
#   │ CONTROL      │ CLEANER      │ MONITOR      │
#   │ (you type)   │ (ground)     │ (ground)     │
#   └──────────────┴──────────────┴──────────────┘
#
#   sender ──UDP──▶ 127.0.0.1:41411 [lossy-relay] ──▶ 127.0.0.1:41410 receiver
#      ▲                                                      │
#      └──── retransmit requests (Unix socket) ◀── cleaner ◀──┘
#
# Usage:  ./run.sh [LOSS_PERCENT]        (default 20)
#         ./run.sh stop
set -euo pipefail

SESSION=parachuter
LOSS="${1:-20}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEMO="$(cd "$HERE/.." && pwd)"
REPO="$(cd "$DEMO/.." && pwd)"
STATE=/tmp/parachuter-demo      # short path: Unix socket paths are length-limited on macOS

if [[ "$LOSS" == "stop" ]]; then
  tmux kill-session -t "$SESSION" 2>/dev/null && echo "demo stopped" || echo "demo was not running"
  exit 0
fi

if ! command -v tmux >/dev/null 2>&1; then
  echo "This demo lays out six panes with tmux. Install it first:  brew install tmux"
  exit 1
fi

# ---------------------------------------------------------------- binaries
if [[ -n "${PARACHUTER:-}" ]]; then
  BIN="$PARACHUTER"
elif command -v parachuter >/dev/null 2>&1; then
  BIN="$(command -v parachuter)"          # e.g. from `cargo install parachuter`
else
  echo "▸ building parachuter from $REPO"
  (cd "$REPO" && cargo build --release -q -p parachuter)
  BIN="$REPO/target/release/parachuter"
fi
echo "▸ building lossy-relay"
(cd "$DEMO" && cargo build --release -q --bin lossy-relay)
RELAY="$DEMO/target/release/lossy-relay"

# ---------------------------------------------------------------- fresh state
tmux kill-session -t "$SESSION" 2>/dev/null || true
rm -rf "$STATE"
mkdir -p "$STATE"/{queue/science,queue/bulk,holding,downloads,files}

cat > "$STATE/config.toml" <<EOF
# Generated by demo/live/run.sh. Edit it while the demo runs: the daemons
# hot-reload it within about a second.

[sender]
bind_ip = "127.0.0.1"
bind_port = 34646
chunk_size = 4096
active_link = "demo"
ledger_path = "$STATE/ledger.sqlite"
priority_dirs = ["$STATE/queue/science", "$STATE/queue/bulk"]
priority_dirs_debug = []
include_extensions = []
skip_extensions = []
control_socket = "$STATE/sender.sock"
initial_state = "auto"
images_per_dark = 50
images_per_flat = 50
images_per_bias = 50
recheck_period_secs = 2
status_dump_period_secs = 86400

[receiver]
bind_ip = "127.0.0.1"
bind_port = 41410
holding_dir = "$STATE/holding"
final_dir = "$STATE/downloads"
control_socket = "$STATE/receiver.sock"

[cleaner]
holding_dir = "$STATE/holding"
final_dir = "$STATE/downloads"
sender_control_socket = "$STATE/sender.sock"
active_link = "demo"
state_path = "$STATE/cleaner-state.json"
run_period_secs = 3
reconcile_period_secs = 21600
reconcile_grace_secs = 10800
dedup_ttl_secs = 6
control_socket = "$STATE/cleaner.sock"

[cleaner.links.demo]
max_in_flight = 40
min_period_ms = 50

[cleaner.links.tdrss]
max_in_flight = 2
min_period_ms = 1000

# Both links point at the lossy relay; they differ only in speed budget,
# so switching to tdrss with ctl set-link visibly slows the stream.
[links.demo]
ip = "127.0.0.1"
port = 41411
max_kbps = 1500
note = "Demo link through lossy-relay"

[links.tdrss]
ip = "127.0.0.1"
port = 41411
max_kbps = 250
note = "Satellite-speed budget, same relay"
EOF

# A couple of sample files to send if you don't have your own handy.
head -c 1500000 /dev/urandom > "$STATE/files/science-frame-001.fits"
head -c 3000000 /dev/urandom > "$STATE/files/gopro-clip-001.mp4"

# Helpers for the CONTROL pane.
cat > "$STATE/helpers.sh" <<EOF
export BASH_SILENCE_DEPRECATION_WARNING=1
export PS1="\[\e[33m\]control\[\e[0m\] \$ "
P="$BIN"
S="$STATE"
ctl()     { "\$P" ctl -s "\$S/sender.sock" "\$@"; }
send()    { for f in "\$@"; do cp "\$f" "\$S/queue/science/"; echo "queued \$(basename "\$f") in the science folder"; done; }
bulk()    { for f in "\$@"; do cp "\$f" "\$S/queue/bulk/"; echo "queued \$(basename "\$f") in the bulk folder"; done; }
landed()  { find "\$S/downloads" -type f | while read -r f; do printf "  %-28s %s\n" "\$(basename "\$f")" "\$(du -h "\$f" | cut -f1)"; done; }
demo()    { bulk "\$S/files/gopro-clip-001.mp4"; send "\$S/files/science-frame-001.fits"; }
verify()  { find "\$S/downloads" -type f | while read -r got; do
              orig="\${got#\$S/downloads}"; name=\$(basename "\$got")
              if cmp -s "\$orig" "\$got"; then echo "✅ \$name is byte-for-byte identical"; else echo "❌ \$name differs"; fi
            done; }
stop()    { tmux kill-session -t $SESSION; }
clear
cat <<'TXT'
 🪂 parachuter live demo: you are the operator

   send FILE...        drop files in the science queue (highest priority)
   bulk FILE...        drop files in the bulk queue (sent after science)
   demo                send the two sample files (a science frame and a GoPro clip)

   ctl status                          what the sender is doing right now
   ctl set-link --link tdrss           switch to the slow link (250 kbps)
   ctl set-link --link demo            back to the fast link (1500 kbps)
   ctl set-link --kbps 400             change the speed cap directly
   ctl set-state paused  / auto        pause and resume the sender

   landed              list files that arrived on the ground
   verify              check each one is byte-for-byte identical
   stop                end the demo

   In the LOSSY LINK pane, type a number + Enter to change the loss rate.
TXT
echo
EOF

# ---------------------------------------------------------------- panes
title() { tmux select-pane -t "$1" -T "$2"; }

tmux new-session -d -s "$SESSION" -x 240 -y 64 -n demo
tmux set -t "$SESSION" pane-border-status top
tmux set -t "$SESSION" pane-border-format " #{pane_title} "
tmux set -t "$SESSION" mouse on

# 0 sender | 1 link | 2 receiver / 3 control | 4 cleaner | 5 monitor
tmux split-window -t "$SESSION" -v
tmux split-window -t "$SESSION:0.0" -h
tmux split-window -t "$SESSION:0.0" -h
tmux split-window -t "$SESSION:0.3" -h
tmux split-window -t "$SESSION:0.3" -h
tmux select-layout -t "$SESSION" tiled

title 0 "SENDER - flight computer"
title 1 "LOSSY LINK - the radio, ${LOSS}% loss (type a new % + Enter)"
title 2 "RECEIVER - ground station"
title 3 "CONTROL - you are the operator"
title 4 "CLEANER - finds gaps, asks for retransmits"
title 5 "MONITOR - files in flight"

tmux send-keys -t "$SESSION:0.2" "clear; '$BIN' receiver -c '$STATE/config.toml'" C-m
tmux send-keys -t "$SESSION:0.1" "clear; '$RELAY' --loss $LOSS" C-m
tmux send-keys -t "$SESSION:0.0" "clear; sleep 1; '$BIN' sender -c '$STATE/config.toml'" C-m
tmux send-keys -t "$SESSION:0.4" "clear; sleep 2; RUST_LOG=info '$BIN' cleaner -c '$STATE/config.toml'" C-m
tmux send-keys -t "$SESSION:0.5" "sleep 2; '$BIN' monitor -s '$STATE/receiver.sock' --period-ms 300" C-m
tmux send-keys -t "$SESSION:0.3" "exec bash --rcfile '$STATE/helpers.sh' -i" C-m
tmux select-pane -t "$SESSION:0.3"

if [[ -n "${TMUX:-}" ]]; then
  tmux switch-client -t "$SESSION"
else
  tmux attach -t "$SESSION"
fi
